[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]

[rpc_endpoints]
chiado = "${CHIADO_RPC_URL}"
gnosis = "${GNOSIS_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
